routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\CommentHeartController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PaginationController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\StripeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/search', [HomeController::class, 'search']);
//Route::post('/search', [HomeController::class, 'search']);
//Route::post('/', [HomeController::class, 'pagination']);

Route::resource('products', ProductController::class);
Route::post('/storeAjax', [ProductController::class,'storeAjax']);
Route::delete('/deleteImage/{id}', [ProductController::class,'deleteImage'])->name('deleteImage');

Route::get('/cart', [CartController::class, 'cart'])->name('cart');
Route::get('/addToCart/{id}', [CartController::class, 'addToCart'])->name('addToCart');
Route::get('/buyNow/{id}', [CartController::class, 'buyNow'])->name('buyNow');

Route::post('/storeCommentsAjax', [CommentController::class,'storeCommentsAjax']);
Route::post('/storeCommentReplyAjax', [CommentController::class,'storeCommentReplyAjax']);

Route::post('/starRate', [RatingController::class,'starRate']);

Route::post('/commentHeart', [CommentHeartController::class,'commentHeart']);
Route::post('/commentReplyHeart', [CommentHeartController::class,'commentReplyHeart']);

Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
Route::post('/profile/update', [ProfileController::class, 'update'])->name('profile.update');
Route::post('/remove-from-cart', [ProductController::class, 'removeFromCart'])->name('remove');
Route::patch('/update-cart', [ProductController::class, 'updateFromCart'])->name('updateFromCart');

Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');
//Route::get('checkout', [StripeController::class, 'checkout'])->name('stripe.checkout');
//Route::post('stripe', [StripeController::class, 'stripePost'])->name('stripe.post');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $dates = ['deleted_at'];

    protected $fillable = [
        'user_id',
        'title',
        'price',
        'quantity',
        'description',
        'views_count'
    ];
// One of metrhods get 'ratings' count
//    protected $withCount = [
//        'ratings'
//    ];

    public function productImage()
    {
        return $this->hasOne(Image::class,"products_id")->oldest();
    }

    public function productImages()
    {
        return $this->hasMany(Image::class,"products_id");
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, "products_id")->latest();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class, "products_id")->latest();
    }

    public function rating()
    {
        return $this->hasOne(Rating::class,"products_id")->latest();
    }

//    public function getRateCountAttribute()
//    {
//        $this->rating()->count();
//    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\ProductJob;
use App\Models\CommentHeart;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\File;
use Illuminate\Contracts\Validation\Rule;
use Illuminate\Support\Facades\DB;
use App\Models\Image;
use App\Models\Product;
use App\Models\User;
use App\Models\Comment;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    static $search;

//    /**
//     * Create a new controller instance.
//     *
//     * @return void
//     */
//    public function __construct()
//    {
//        $this->middleware('auth');
//    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = auth()->user()->id;
        ProductController::$search = $request->input('search');

        if(ProductController::$search != ""){

            $products = Product::where('user_id', $user)
                ->where(function($query) {
                    $query->where('title','LIKE', '%'.ProductController::$search.'%')
                        ->orWhere('description','LIKE', '%'.ProductController::$search.'%')
                        ->orWhere('price','LIKE', '%'.ProductController::$search.'%')
                        ->orWhere('quantity','LIKE', '%'.ProductController::$search.'%');
                })
                ->with("productImage")
                ->latest()->paginate(5);
        } else {
            $products = Product::where('user_id', $user)->with("productImage")->latest()->paginate(5);
        }

        return view('pages.products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'min:3'],
            'price' => ['required', 'numeric'],
            'quantity' => ['required', 'integer'],
            'description' => ['required','min:20'],
            'imageFile' => 'required',
            'imageFile.*' => ['required','image','mimes:jpg,png,jpeg,gif,svg|max:2048']
        ]);


        $input = $request->all();

        $product = new Product;
        $product->title = $input['title'];
        $product->user_id = $input['user_id'];
        $product->price = $input['price'];
        $product->quantity = $input['quantity'];
        $product->description = $input['description'];
        $product->save();

        if ($request->hasfile('imageFile')) {
            foreach($request->file('imageFile') as $kay=>$file)
            {
                $fileName = date('YmdHis') . "_" .$kay . "_" . $file->getClientOriginalName();
                $file->storeAs('products', $fileName, 'public');

                $image = new Image;
                $image->user_id = $input['user_id'];
                $image->products_id = $product->id;
                $image->name = $fileName;
                $image->image_path = public_path() . '/storage/products/'. $fileName;
                $image->save();
            }
        }

        return redirect()->route('products.index')
            ->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Product::where('id', $id)->first()->increment('views_count');

        $product = Product::with("productImages")
            ->with("comments")
            ->with("ratings")
            ->where('id', $id)->first();

        return view('pages.products.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::where('id', $id)->first();
        $images = Image::where('products_id', $id)->get();

        return view('pages.products.edit',compact('product','images'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product, Image $images)
    {
        $request->validate([
            'title' => ['required', 'min:3'],
            'price' => ['required', 'numeric'],
            'quantity' => ['required', 'integer'],
            'description' => ['required','min:20'],
            'imageFile.*' => ['image','mimes:jpg,png,jpeg,gif,svg|max:2048']
        ]);

        $input = $request->all();
        $product->update($input);

        if ($request->hasfile('imageFile')) {
            foreach($request->file('imageFile') as $kay=>$file)
            {
                $fileName = date('YmdHis') . "_" .$kay . "_" . "2" . "_" .$file->getClientOriginalName();
                $file->storeAs('products', $fileName, 'public');

                $images = new Image;
                $images->user_id = $product->user_id;
                $images->products_id = $product->id;
                $images->name = $fileName;
                $images->image_path = public_path() . '/storage/products/'. $fileName;
                $images->save();
            }
        }


        return redirect()->route('products.index')
            ->with('success','Product updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request ,Product $product)
    {
        $images = Image::where('products_id', $product->id)->get();


        if($images){
            foreach ($images as $image){
                unlink(public_path().'/storage/products/'. $image->name);
            }
        }

        $product->delete();
        Image::where('products_id', $product->id)->delete();
        Comment::where('products_id', $product->id)->delete();

        return redirect()->route('products.index')
            ->with('success','Product deleted successfully.');
    }

    public function storeAjax(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => ['required', 'min:3'],
            'price' => ['required', 'numeric'],
            'quantity' => ['required', 'integer'],
            'description' => ['required', 'min:20']
        ]);

        if ($validator->fails()) {
            return response()->json([
                'status'=>400,
                'error'=>$validator->errors()->toArray()
            ]);
        }else{
            $input = $request->all();

            $product = new Product;
            $product->title = $input['title'];
            $product->user_id = $input['user_id'];
            $product->price = $input['price'];
            $product->quantity = $input['quantity'];
            $product->description = $input['description'];
            $product->views_count = 0;
            $product->save();

            $filesArr = $input['filesArr'];

            if (count($filesArr) > 0) {
                foreach ($filesArr as $kay => $file) {
                    $fileName = date('YmdHis') . "_" . $kay . "_" . $file['name'];

                    $path = str_replace("\\", "/", public_path());

                    $image_tmp = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $file['data']));
                    file_put_contents($path . '/storage/products/' . $fileName, $image_tmp);

                    $images = new Image;
                    $images->user_id = $input['user_id'];
                    $images->products_id = $product->id;
                    $images->name = $fileName;
                    $images->image_path = $path . '/storage/products/' . $fileName;
                    $images->save();
                }

                return response()->json([
                    'status'=>200 ,
                    'message'=>'New product was created.'
                ]);
            }
        }

    }

    public function deleteImage($id)
    {
        $images = Image::where('id', $id)->get();
        if($images){
            foreach ($images as $image){
                unlink(public_path().'/storage/products/'. $image->name);
            }
        }
        Image::where('id', $id)->delete();

        return back();
    }
}

resources/views/pages/products/create.blade.php
@extends('layouts.app')

@section('content')

{{--    @if ($errors->any())--}}
{{--        <div class="alert alert-danger">--}}
{{--            <strong>Whoops!</strong> There were some problems with your input.<br><br>--}}
{{--            <ul>--}}
{{--                @foreach ($errors->all() as $error)--}}
{{--                    <li>{{ $error }}</li>--}}
{{--                @endforeach--}}
{{--            </ul>--}}
{{--        </div>--}}
{{--    @endif--}}

    <style>
        .imgPreview img {
            padding: 8px;
            max-width: 80px;
        }
    </style>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
{{--                            @if (session('status'))--}}
{{--                                <div class="alert alert-success" role="alert">--}}
{{--                                    {{ session('status') }}--}}
{{--                                </div>--}}
{{--                            @endif--}}
                            <div class="col-6">
                                <h3 class="fw-normal text-secondary fs-4 text-uppercase mb-4">Add new item</h3>
                                    {{--Validation output--}}
                                <ul id="form_err"></ul>
                                <div id="success_message"></div>
                            </div>
                            <form class="needs-validation" name="store" id="storeAjax">
                                @csrf

                                <input type="hidden" class="form-control" id="user_id" name="user_id" value="{{auth()->user()->id}}">
                                <div class="col-3 mb-3">
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                                    <snap class="text-danger error-text title_error" id="title_error"></snap>
                                </div>
                                <div class="col-3 mb-3">
                                    <input type="text" class="form-control" id="price" name="price" placeholder="Price">
                                    <snap class="text-danger error-text price_error" id="price_error"></snap>
                                </div>
                                <div class="col-3 mb-3">
                                    <input type="text" class="form-control" id="quantity" name="quantity" placeholder="Quantity">
                                    <snap class="text-danger error-text quantity_error" id="quantity_error"></snap>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <textarea class="form-control" id="description" name="description" placeholder="Description" rows="3"></textarea>
                                    <snap class="text-danger error-text description_error" id="description_errorr"></snap>
                                </div>
                                {{--Image preview--}}
                                <div class="col-md-12 mb-1">
                                    <div class="user-image mb-3 text-center">
                                        <div class="imgPreview">
                                        </div>
                                    </div>

                                    <div class="input-group mb-3">
                                        <input type="hidden" name="imageNames" value="" id="imageNames">
                                        <input type="file" name="imageFile[]" class="form-control" id="images" multiple="multiple">
                                        <label class="input-group-text" for="images">Upload</label>
                                        <snap class="text-danger error-text imageFile_error"></snap>
                                    </div>
                                </div>
                                <div class="col-12 mt-b">
                                    <button class="btn btn-primary float-end">Submit</button>
                                    <button id="cancelButton" type="button" class="btn btn-outline-secondary float-end me-2">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

resources/views/pages/products/edit.blade.php
@extends('layouts.app')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <div class="col-6">
                                <h3 class="fw-normal text-secondary fs-4 text-uppercase mb-4">Edit item</h3>
                            </div>

                            <form action="{{route('products.update',$product->id)}}" class="needs-validation" name="update" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="{{$product->title}}">
                                        </div>
                                        <div class="w-100"></div>
                                        <div class="col-md-6 mb-3">
                                            <input type="text" class="form-control" id="price" name="price" placeholder="Price" value="{{$product->price}}">
                                        </div>
                                        <div class="w-100"></div>
                                        <div class="col-md-6 mb-3">
                                            <input type="text" class="form-control" id="quantity" name="quantity" placeholder="Quantity" value="{{$product->quantity}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-12 mb-3">
                                    <textarea class="form-control" id="description" name="description" placeholder="Description" rows="3">{{$product->description}}</textarea>
                                </div>

                                <div class="w-100"></div>

                                <div class="col-md-12 mb-1">
                                    <div class="custom-file">
                                        <input type="file" name="imageFile[]" class="custom-file-input" id="images" multiple="multiple">
                                        <label class="custom-file-label" for="images">Upload</label>
                                    </div>
                                </div>

                                <div class="w-100"></div>

                                <div class="col-12 mt-b">
                                    <input id="submitInput" type="submit" value="Edit" class="btn btn-primary float-end" name="submit">
                                    <button type="button" class="btn btn-outline-secondary float-end me-2" id="goBackEdit">Cancel</button>
                                </div>
                            </form>

                            <div class="col-md-12">
                                <table class="table table-bordered">
                                    <tr>
                                        <th><span class="ml-2">Image</span></th>
                                        <th><span class="ml-2">Name</span></th>
                                    </tr>
                                    @if(!empty($product->productImages))
                                        @foreach($product->productImages as $key => $image)
                                            <tr>
                                                <td>
                                                    <img src="{{asset('/storage/products/'. $image->name)}}" width="70"></li>
                                                </td>
                                                <td class="col-3">
                                                    <form action="{{ route('deleteImage',$image->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(function() {
        $('button#goBackEdit').on('click', function(e){
            e.preventDefault();
            window.history.back();
        });
    });
</script>

resources/views/pages/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" style="padding: 30px 0;">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header-heading">
                        <div class="row">
                            @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    {{ session('status') }}
                                </div>
                            @endif

                            @if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
                            <div>
                                <form class="float-right m-3" method="GET" action="">
                                    <div class="form-group">
                                        <input type="search" class="form-control" name="search" placeholder="Search..."/>
                                    </div>

                                    <button class="btn btn-outline-dark" type="submit">Search</button>
                                    <a href="{{route('products.index')}}" class="btn btn-outline-dark">
                                        Reset
                                    </a>

                                </form>
                                <div class="float-right m-3">
                                    <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th><span class="ml-2">No</span></th>
                                        <th><span class="ml-2">Image</span></th>
                                        <th><span class="ml-2">Name</span></th>
                                        <th><span class="ml-2">Quantity</span></th>
                                        <th><span class="ml-2">Details</span></th>
                                        <th><span class="ml-2">Action</span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($products as $product)
                                    <tr>
                                        <td>{{ ++$i }}</td>
                                        <td>
                                            @if($product->productImage->name !== 'No-image-available.png')
                                                <img src="{{asset('/storage/products/'. $product->productImage->name)}}" width="100px">
                                            @else
                                                <img src="{{asset('/storage/no_image/No-image-available.png')}}" width="100px">
                                            @endif
                                        </td>

                                        <td>{{ $product->title }}</td>
                                        <td>
                                            @if($product->quantity == "0")
                                                <p style="color: red;">Out of stock</p>
                                            @else
                                                {{ $product->quantity }}
                                            @endif
                                        </td>
                                        <td style="word-break: break-word">{{ $product->description }}</td>
                                        <td class="col-3">
                                            <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                                                @csrf
                                                <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>

                                                <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>

                                                @method('DELETE')

                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            {!! $products->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection